"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for line in path.read_text(encoding='utf-8').splitlines():
        raw = line.strip()
        if not raw or raw.startswith('#') or '=' not in raw:
            continue
        key, value = raw.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


env_file_override = os.getenv('DJANGO_ENV_FILE')
if env_file_override:
    load_env_file(Path(env_file_override))
else:
    load_env_file(BASE_DIR / '.env')


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: list[str] | None = None) -> list[str]:
    raw = os.getenv(name)
    if raw is None:
        return default or []
    return [item.strip() for item in raw.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'dev-only-not-for-production-6f4e1f41c9a74b13b945b1d146e0cb6d9f2a5c03',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', [
    '127.0.0.1',
    'localhost',
    'testserver',
])

CSRF_TRUSTED_ORIGINS = env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    default_csrf_trusted_origins if DEBUG else [],
)

# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "reves.apps.RevesConfig",
    'pwa',
    'webpush',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

if DEBUG:
    INSTALLED_APPS.append('debug_toolbar')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Servir les fichiers statiques en production
    'reves.middleware.RequestAuditLogMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Configuration flexible : PostgreSQL en production, SQLite en développement

def _get_database_config() -> dict:
    """Retourne la config DB selon l'env. PostgreSQL en prod, SQLite en dev."""
    db_engine = os.getenv('DATABASE_ENGINE', 'django.db.backends.sqlite3')
    
    if db_engine == 'django.db.backends.postgresql':
        return {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.getenv('DATABASE_NAME', 'reves_prod'),
                'USER': os.getenv('DATABASE_USER', 'reves_user'),
                'PASSWORD': os.getenv('DATABASE_PASSWORD', ''),
                'HOST': os.getenv('DATABASE_HOST', 'localhost'),
                'PORT': os.getenv('DATABASE_PORT', '5432'),
                'ATOMIC_REQUESTS': True,  # Transactions atomiques par requête
                'CONN_MAX_AGE': 600,  # Connection pooling (10 min)
            }
        }
    elif db_engine == 'django.db.backends.mysql':
        return {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': os.getenv('DATABASE_NAME', 'reves_prod'),
                'USER': os.getenv('DATABASE_USER', 'reves_user'),
                'PASSWORD': os.getenv('DATABASE_PASSWORD', ''),
                'HOST': os.getenv('DATABASE_HOST', 'localhost'),
                'PORT': os.getenv('DATABASE_PORT', '3306'),
                'ATOMIC_REQUESTS': True,
                'CONN_MAX_AGE': 600,
                'OPTIONS': {
                    'charset': 'utf8mb4',
                }
            }
        }
    else:  # Default SQLite pour développement
        return {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

DATABASES = _get_database_config()

# Validation : en production, PostgreSQL ou MySQL est exigé pour la stabilité
if not DEBUG and DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    raise ValueError(
        'SQLite is not recommended for production. '
        'Set DATABASE_ENGINE to "django.db.backends.postgresql" or "django.db.backends.mysql" '
        'and configure the other DATABASE_* environment variables.'
    )


# =============================================================================
# UNFOLD CONFIGURATION (django-unfold)
# =============================================================================

UNFOLD = {
    "STYLES": {
        "dashboard_filters_row": {"display": "grid", "grid-template-columns": "repeat(auto-fit, minmax(200px, 1fr))", "gap": "12px"},
    },
    "COLORS": {
        "base": {
            "50": "#f8f9fa",
            "100": "#f0f2f5",
            "200": "#e9ecef",
            "300": "#dee2e6",
            "400": "#ced4da",
            "500": "#adb5bd",
            "600": "#6c757d",
            "700": "#495057",
            "800": "#343a40",
            "900": "#212529",
        },
        "primary": {
            "50": "#eff6ff",
            "100": "#dbeafe",
            "200": "#bfdbfe",
            "300": "#93c5fd",
            "400": "#60a5fa",
            "500": "#3b82f6",
            "600": "#2563eb",
            "700": "#1d4ed8",
            "800": "#1e40af",
            "900": "#1e3a8a",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Utilisateurs",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Utilisateurs",
                        "icon": "account_circle",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Groupes",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                    {
                        "title": "Profils",
                        "icon": "people",
                        "link": reverse_lazy("admin:reves_profil_changelist"),
                    },
                ],
            },
            {
                "title": "Questionnaires",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "analytics",
                        "link": reverse_lazy("admin:reves_questionnaire_dashboard"),
                    },
                    {
                        "title": "Data (lignes)",
                        "icon": "description",
                        "link": reverse_lazy("admin:reves_questionnaire_changelist"),
                    },
                ],
            },
            {
                "title": "Contenu & Rêves",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Rêves dashboard",
                        "icon": "analytics",
                        "link": reverse_lazy("admin:reves_reve_dashboard"),
                    },
                    {
                        "title": "Rêves data (lignes)",
                        "icon": "favorite",
                        "link": reverse_lazy("admin:reves_reve_changelist"),
                    },
                    {
                        "title": "Émotions de référence",
                        "icon": "mood",
                        "link": reverse_lazy("admin:reves_reveemotion_changelist"),
                    },
                    {
                        "title": "Modalités visuelles",
                        "icon": "visibility",
                        "link": reverse_lazy("admin:reves_reveimagemodalite_changelist"),
                    },
                    {
                        "title": "Émotions personnalisées",
                        "icon": "sentiment_satisfied",
                        "link": reverse_lazy("admin:reves_reveemotioncustom_changelist"),
                    },
                    {
                        "title": "Éléments personnalisés",
                        "icon": "category",
                        "link": reverse_lazy("admin:reves_reveelementcustom_changelist"),
                    },
                    {
                        "title": "Notifications",
                        "icon": "notifications",
                        "link": reverse_lazy("admin:reves_notification_changelist"),
                    },
                ],
            },
        ],
    },
    "DASHBOARD": {
        "columns": 3,
        "widgets": [],
    },
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True

# LOGIN
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/journal/"
LOGOUT_REDIRECT_URL = "/"


# Media files (User uploads)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise pour servir les statics en production (optionnel mais recommandé)
# Installer avec : pip install whitenoise
# Puis ajouter 'whitenoise.middleware.WhiteNoiseMiddleware' au début de MIDDLEWARE

# Django Debug Toolbar
INTERNAL_IPS = [
    '127.0.0.1',
]


# Email Configuration
# https://docs.djangoproject.com/en/6.0/topics/email/

EMAIL_BACKEND = os.getenv(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.getenv('DJANGO_EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('DJANGO_EMAIL_PORT', '587'))
EMAIL_USE_TLS = env_bool('DJANGO_EMAIL_USE_TLS', True)
EMAIL_HOST_USER = os.getenv('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('DJANGO_EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DJANGO_DEFAULT_FROM_EMAIL', 'noreply@reves-etude.fr')


# SESSION & COOKIES CONFIGURATION
# https://docs.djangoproject.com/en/6.0/topics/http/sessions/

# Durée de la session : 30 jours (en secondes)
SESSION_COOKIE_AGE = 30 * 24 * 60 * 60  # 30 days

# Les cookies persistent même après la fermeture du navigateur
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Nom du cookie de session
SESSION_COOKIE_NAME = 'reves_sessionid'

# Le cookie n'est accessible que via HTTP (protection contre XSS)
SESSION_COOKIE_HTTPONLY = True

# S'assurer que le cookie est envoyé seulement en HTTPS en production
SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', not DEBUG)

# SameSite protection contre les attaques CSRF
SESSION_COOKIE_SAMESITE = 'Lax'

# Sauvegarder la session en base de données
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Mettre à jour la session à chaque requête (glisse la fenêtre de 30j à chaque visite)
SESSION_SAVE_EVERY_REQUEST = True

# ─────────────────────────────────────────────────────────────────────────────
# CSRF COOKIE CONFIGURATION
# Nécessaire pour que la PWA (service worker) ne casse pas le token CSRF
# ─────────────────────────────────────────────────────────────────────────────

# False OBLIGATOIRE : le JS doit pouvoir lire le cookie CSRF pour l'injecter
# dans les requêtes fetch/AJAX (notamment depuis le service worker)
CSRF_COOKIE_HTTPONLY = False

# HTTPS only en production (même logique que le cookie de session)
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', not DEBUG)

# Lax = cookie envoyé pour toutes les requêtes same-site + navigations top-level
# Compatible PWA standalone (considérée same-site par le navigateur)
CSRF_COOKIE_SAMESITE = 'Lax'


# SECURITY HARDENING
# https://docs.djangoproject.com/en/6.0/ref/middleware/#security-middleware
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = env_bool('DJANGO_USE_X_FORWARDED_HOST', False)
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', not DEBUG)
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', not DEBUG)
SECURE_HSTS_PRELOAD = env_bool('DJANGO_SECURE_HSTS_PRELOAD', not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = env_bool('DJANGO_SECURE_CONTENT_TYPE_NOSNIFF', True)
X_FRAME_OPTIONS = os.getenv('DJANGO_X_FRAME_OPTIONS', 'DENY')
SECURE_REFERRER_POLICY = os.getenv('DJANGO_SECURE_REFERRER_POLICY', 'strict-origin-when-cross-origin')
SECURE_CROSS_ORIGIN_OPENER_POLICY = os.getenv('DJANGO_SECURE_CROSS_ORIGIN_OPENER_POLICY', 'same-origin')

# Password reset token validity (24h)
PASSWORD_RESET_TIMEOUT = int(os.getenv('DJANGO_PASSWORD_RESET_TIMEOUT', str(60 * 60 * 24)))

# =============================================================================
# PWA CONFIGURATION (django-pwa)
# =============================================================================

PWA_APP_NAME = 'Journal des Rêves'
PWA_APP_DESCRIPTION = "Enregistre et explore tes rêves chaque nuit"
PWA_APP_THEME_COLOR = '#1a1a2e'
PWA_APP_BACKGROUND_COLOR = '#1a1a2e'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/reves/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/reves/enregistrer/'
PWA_APP_STATUS_BAR_COLOR = 'black-translucent'
PWA_APP_LANG = 'fr-FR'
PWA_APP_DIR = 'ltr'
PWA_APP_DEBUG_MODE = False

PWA_APP_ICONS = [
    {'src': '/static/reves/icons/icon-72x72.png',   'sizes': '72x72'},
    {'src': '/static/reves/icons/icon-96x96.png',   'sizes': '96x96'},
    {'src': '/static/reves/icons/icon-128x128.png', 'sizes': '128x128'},
    {'src': '/static/reves/icons/icon-144x144.png', 'sizes': '144x144'},
    {'src': '/static/reves/icons/icon-152x152.png', 'sizes': '152x152'},
    {'src': '/static/reves/icons/icon-192x192.png', 'sizes': '192x192'},
    {'src': '/static/reves/icons/icon-384x384.png', 'sizes': '384x384'},
    {'src': '/static/reves/icons/icon-512x512.png', 'sizes': '512x512'},
]

PWA_APP_ICONS_APPLE = [
    {'src': '/static/reves/icons/apple-touch-icon.png', 'sizes': '180x180'},
]

PWA_APP_SHORTCUTS = [
    {
        'name': 'Enregistrer un rêve',
        'url': '/reves/enregistrer/',
        'description': 'Enregistre ton rêve directement',
    },
    {
        'name': 'Mon journal',
        'url': '/reves/journal/',
        'description': 'Voir tous mes rêves',
    },
]

# Service worker personnalisé (cache les assets du site)
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'reves', 'templates', 'reves', 'sw.js')

# =============================================================================
# WEBPUSH CONFIGURATION (django-webpush)
# =============================================================================

WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": os.getenv("VAPID_PUBLIC_KEY", "BP_eLOKiWEmrMMneU-cXcqwxHhkAYkVlLmoKq7HmPelOqfVCWP9OqBfgIflLik51C2uPbLqalZMWdqg8--7d9Pc"),
    "VAPID_PRIVATE_KEY": os.getenv("VAPID_PRIVATE_KEY", "uHSMq-Hdu3YFNky8WpRb5x6DUxblAtLhwrZOsQvhtd0"),
    "VAPID_ADMIN_EMAIL": os.getenv("VAPID_ADMIN_EMAIL", "contact@reves-etude.fr"),
}

LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(parents=True, exist_ok=True)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'application_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(LOGS_DIR / 'application.log'),
            'when': 'midnight',
            'backupCount': int(os.getenv('DJANGO_LOG_BACKUP_COUNT', '30')),
            'encoding': 'utf-8',
            'formatter': 'standard',
        },
        'access_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(LOGS_DIR / 'access.log'),
            'when': 'midnight',
            'backupCount': int(os.getenv('DJANGO_LOG_BACKUP_COUNT', '30')),
            'encoding': 'utf-8',
            'formatter': 'standard',
        },
        'security_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(LOGS_DIR / 'security.log'),
            'when': 'midnight',
            'backupCount': int(os.getenv('DJANGO_LOG_BACKUP_COUNT', '60')),
            'encoding': 'utf-8',
            'formatter': 'standard',
        },
        'transcription_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(BASE_DIR / 'transcription.log'),
            'when': 'midnight',
            'backupCount': int(os.getenv('DJANGO_LOG_BACKUP_COUNT', '30')),
            'encoding': 'utf-8',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'application_file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'application_file'],
            'level': os.getenv('DJANGO_REQUEST_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'application_file'],
            'level': os.getenv('DJANGO_SERVER_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'security_file'],
            'level': os.getenv('DJANGO_SECURITY_LOG_LEVEL', 'WARNING'),
            'propagate': False,
        },
        'django.contrib.auth': {
            'handlers': ['console', 'security_file'],
            'level': os.getenv('DJANGO_AUTH_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.access': {
            'handlers': ['console', 'access_file'],
            'level': os.getenv('DJANGO_ACCESS_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'transcription': {
            'handlers': ['console', 'transcription_file'],
            'level': os.getenv('DJANGO_TRANSCRIPTION_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

