"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gz)s!op#n*v3a9#zwx3+j6hi^0-bp$u-=n=uci9n7h312#@w)9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow all hosts in development

# Autoriser les domaines de tunnel HTTPS (ngrok) pour les POST CSRF
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.dev',
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
]


# Application definition

INSTALLED_APPS = [
    "polls.apps.PollsConfig",
    'pwa',
    'webpush',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# LOGIN
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/polls/journal/"
LOGOUT_REDIRECT_URL = "/polls/"


# Media files (User uploads)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Django Debug Toolbar
INTERNAL_IPS = [
    '127.0.0.1',
]


# Email Configuration
# https://docs.djangoproject.com/en/6.0/topics/email/

# En développement, afficher les emails dans la console
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # En production, configurer un serveur SMTP réel
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'your-email-host'  # À configurer
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'your-email@example.com'  # À configurer
    EMAIL_HOST_PASSWORD = 'your-password'  # À configurer

DEFAULT_FROM_EMAIL = 'noreply@reves-etude.fr'


# SESSION & COOKIES CONFIGURATION
# https://docs.djangoproject.com/en/6.0/topics/http/sessions/

# Durée de la session : 30 jours (en secondes)
SESSION_COOKIE_AGE = 30 * 24 * 60 * 60  # 30 days

# Les cookies persistent même après la fermeture du navigateur
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Nom du cookie de session
SESSION_COOKIE_NAME = 'reves_sessionid'

# Le cookie n'est accessible que via HTTP (protection contre XSS)
SESSION_COOKIE_HTTPONLY = True

# S'assurer que le cookie est envoyé seulement en HTTPS en production
SESSION_COOKIE_SECURE = not DEBUG  # True en production, False en développement

# SameSite protection contre les attaques CSRF
SESSION_COOKIE_SAMESITE = 'Lax'

# Sauvegarder la session en base de données
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Mettre à jour la session à chaque requête (glisse la fenêtre de 30j à chaque visite)
SESSION_SAVE_EVERY_REQUEST = True

# Se souvenir de l'utilisateur lors de la connexion (remember me)
# Les utilisateurs peuvent cocher "Remember me" lors de la connexion
REMEMBER_ME_DURATION = 30 * 24 * 60 * 60  # 30 days

# ─────────────────────────────────────────────────────────────────────────────
# CSRF COOKIE CONFIGURATION
# Nécessaire pour que la PWA (service worker) ne casse pas le token CSRF
# ─────────────────────────────────────────────────────────────────────────────

# False OBLIGATOIRE : le JS doit pouvoir lire le cookie CSRF pour l'injecter
# dans les requêtes fetch/AJAX (notamment depuis le service worker)
CSRF_COOKIE_HTTPONLY = False

# HTTPS only en production (même logique que le cookie de session)
CSRF_COOKIE_SECURE = not DEBUG

# Lax = cookie envoyé pour toutes les requêtes same-site + navigations top-level
# Compatible PWA standalone (considérée same-site par le navigateur)
CSRF_COOKIE_SAMESITE = 'Lax'

# =============================================================================
# PWA CONFIGURATION (django-pwa)
# =============================================================================
import os

PWA_APP_NAME = 'Journal des Rêves'
PWA_APP_DESCRIPTION = "Enregistre et explore tes rêves chaque nuit"
PWA_APP_THEME_COLOR = '#1a1a2e'
PWA_APP_BACKGROUND_COLOR = '#1a1a2e'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/polls/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/polls/enregistrer/'
PWA_APP_STATUS_BAR_COLOR = 'black-translucent'
PWA_APP_LANG = 'fr-FR'
PWA_APP_DIR = 'ltr'
PWA_APP_DEBUG_MODE = False

PWA_APP_ICONS = [
    {'src': '/static/polls/icons/icon-72x72.png',   'sizes': '72x72'},
    {'src': '/static/polls/icons/icon-96x96.png',   'sizes': '96x96'},
    {'src': '/static/polls/icons/icon-128x128.png', 'sizes': '128x128'},
    {'src': '/static/polls/icons/icon-144x144.png', 'sizes': '144x144'},
    {'src': '/static/polls/icons/icon-152x152.png', 'sizes': '152x152'},
    {'src': '/static/polls/icons/icon-192x192.png', 'sizes': '192x192'},
    {'src': '/static/polls/icons/icon-384x384.png', 'sizes': '384x384'},
    {'src': '/static/polls/icons/icon-512x512.png', 'sizes': '512x512'},
]

PWA_APP_ICONS_APPLE = [
    {'src': '/static/polls/icons/apple-touch-icon.png', 'sizes': '180x180'},
]

PWA_APP_SHORTCUTS = [
    {
        'name': 'Enregistrer un rêve',
        'url': '/polls/enregistrer/',
        'description': 'Enregistre ton rêve directement',
    },
    {
        'name': 'Mon journal',
        'url': '/polls/journal/',
        'description': 'Voir tous mes rêves',
    },
]

# Service worker personnalisé (cache les assets du site)
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'polls', 'templates', 'polls', 'sw.js')

# =============================================================================
# WEBPUSH CONFIGURATION (django-webpush)
# =============================================================================

WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BP_eLOKiWEmrMMneU-cXcqwxHhkAYkVlLmoKq7HmPelOqfVCWP9OqBfgIflLik51C2uPbLqalZMWdqg8--7d9Pc",
    "VAPID_PRIVATE_KEY": "uHSMq-Hdu3YFNky8WpRb5x6DUxblAtLhwrZOsQvhtd0",
    "VAPID_ADMIN_EMAIL": "contact@reves-etude.fr",
}
