---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: db-backup
spec:
  schedule: "30 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: db-backup
              image: postgres:16-alpine
              env:
                - name: POSTGRES_HOST
                  value: 'postgres.journal-des-reves.svc.cluster.local'
                - name: POSTGRES_PORT
                  value: '5432'
                - name: POSTGRES_USER
                  value: 'reves'
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: nocodb
                      key: postgres_password
              args:
                - /bin/bash
                - -c
                - echo "$POSTGRES_HOST:$POSTGRES_PORT:reves:$POSTGRES_USER:$POSTGRES_PASSWORD" > ~/.pgpass; chmod 600 ~/.pgpass; mkdir -p /backup/reves-postgres; find /backup/reves-postgres -mtime +7 -delete; pg_dumpall -h $POSTGRES_HOST -p $POSTGRES_PORT -c | gzip -c > /backup/reves-postgres/dump_postgres_$(date +%F_%H_%M_%S).sql.gz;
              volumeMounts:
                - name: postgres-backup
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: postgres-backup
              persistentVolumeClaim:
                claimName: postgresbackup-pvc
