# Generated by Django 6.0.2 on 2026-02-23 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reve',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='reve',
            name='transcription',
            field=models.TextField(blank=True, help_text='Transcription automatique du rêve', null=True),
        ),
        migrations.AlterField(
            model_name='reve',
            name='audio',
            field=models.FileField(help_text='Enregistrement audio du rêve (WAV)', upload_to='reves_audio/'),
        ),
        migrations.AlterField(
            model_name='reve',
            name='intensite',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
