# Generated by Django 6.0.2 on 2026-02-26 14:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_reve_options_reve_transcription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Tous les jours'), ('often', 'Souvent'), ('sometimes', 'Parfois'), ('rarely', 'Rarement')], max_length=20, verbose_name='Fréquence de rappel des rêves')),
                ('dream_lucide', models.BooleanField(default=False, verbose_name='Rêves lucides')),
                ('dream_recurrent', models.BooleanField(default=False, verbose_name='Rêves récurrents')),
                ('dream_nightmare', models.BooleanField(default=False, verbose_name='Cauchemars')),
                ('dream_pleasant', models.BooleanField(default=False, verbose_name='Rêves agréables')),
                ('sleep_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Bon'), ('average', 'Moyen'), ('poor', 'Mauvais')], max_length=20, verbose_name='Qualité du sommeil')),
                ('sleep_hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Heures de sommeil')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='polls.profil')),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
                'ordering': ['-created_at'],
            },
        ),
    ]
