# Generated by Django 6.0.2 on 2026-02-26 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0004_questionnaire_annee_naissance_questionnaire_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Émotion')),
                ('emoji', models.CharField(default='😐', max_length=10, verbose_name='Emoji représentant')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Émotion',
                'verbose_name_plural': 'Émotions',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.RemoveField(
            model_name='reve',
            name='intensite',
        ),
        migrations.AddField(
            model_name='reve',
            name='etendue_reve',
            field=models.IntegerField(blank=True, choices=[(1, "D'un instant précis"), (2, 'De moins de la moitié du rêve'), (3, 'De plus de la moitié du rêve'), (4, "De l'intégralité ou quasi-totalité du rêve")], null=True, verbose_name='Je me souviens plutôt'),
        ),
        migrations.AddField(
            model_name='reve',
            name='sens',
            field=models.IntegerField(blank=True, choices=[(1, 'Images'), (2, 'Des sons, des voix'), (3, 'Des sensations de mon corps'), (4, 'Des émotions ressenties'), (5, 'Des pensées ou idées')], help_text='Le sens principal dont vous vous souvenez', null=True, verbose_name='Sens principaux'),
        ),
        migrations.AddField(
            model_name='reve',
            name='transcription_ready',
            field=models.BooleanField(default=False, help_text='Indique si la transcription a été générée'),
        ),
        migrations.AddField(
            model_name='reve',
            name='type_reve',
            field=models.CharField(blank=True, choices=[('tres_positif', 'Rêve très positif'), ('positif', 'Rêve positif'), ('neutre', 'Rêve neutre'), ('mauvais', 'Mauvais rêve'), ('cauchemar', 'Cauchemar')], max_length=20, null=True, verbose_name='Type de rêve'),
        ),
        migrations.AlterField(
            model_name='reve',
            name='transcription',
            field=models.TextField(blank=True, help_text='Transcription automatique du rêve (générée par Whisper)', null=True),
        ),
        migrations.AddField(
            model_name='reve',
            name='emotions_reve',
            field=models.ManyToManyField(blank=True, related_name='reves', to='reves.emotion', verbose_name='Émotions ressenties'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='Tag')),
                ('couleur', models.CharField(default='#3245bd', help_text='Couleur en format hex (#RRGGBB)', max_length=7, verbose_name='Couleur du tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='reves.profil')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-created_at'],
                'unique_together': {('profil', 'libelle')},
            },
        ),
        migrations.AddField(
            model_name='reve',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='reves', to='reves.tag', verbose_name='Tags personnalisés'),
        ),
    ]
