# Generated by Django 6.0.2 on 2026-02-26 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0005_emotion_remove_reve_intensite_reve_etendue_reve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='Émotion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions_custom', to='reves.profil')),
            ],
            options={
                'verbose_name': 'Émotion personnalisée',
                'verbose_name_plural': 'Émotions personnalisées',
                'ordering': ['libelle'],
                'unique_together': {('profil', 'libelle')},
            },
        ),
        migrations.AddField(
            model_name='reve',
            name='emotions_custom',
            field=models.ManyToManyField(blank=True, related_name='reves', to='reves.emotioncustom', verbose_name='Émotions personnalisées'),
        ),
    ]
