# Generated by Django 6.0.2 on 2026-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_emotioncustom_reve_emotions_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='consent_data_processing',
            field=models.BooleanField(default=False, help_text="J'accepte que mes données soient traitées par l'équipe de recherche", verbose_name='Accepte le traitement des données'),
        ),
        migrations.AddField(
            model_name='profil',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation du consentement"),
        ),
        migrations.AddField(
            model_name='profil',
            name='consent_password_account',
            field=models.BooleanField(default=False, help_text='Je souscris à un compte spécialisé protégé par un mot de passe', verbose_name='Accepte un compte protégé par mot de passe'),
        ),
        migrations.AddField(
            model_name='profil',
            name='consent_quote_expressions',
            field=models.BooleanField(default=False, help_text="J'autorise qu'une partie de mes expressions puisse être citée", verbose_name="Autorize la citation d'expressions"),
        ),
    ]