# Generated by Django 6.0.2 on 2026-03-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0007_profil_consent_data_processing_profil_consent_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name="Modalité d'image")),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Modalité d'image",
                'verbose_name_plural': "Modalités d'images",
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.AddField(
            model_name='reve',
            name='images_modalites',
            field=models.ManyToManyField(blank=True, help_text='Les modalités des images dont vous vous souvenez (couleur, netteté, etc.)', related_name='reves', to='reves.imagemodalite', verbose_name='Modalités des images'),
        ),
    ]
