# Generated by Django 6.0.2 on 2026-03-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_imagemodalite_reve_images_modalites'),
    ]

    operations = [
        migrations.AddField(
            model_name='reve',
            name='existence_souvenir',
            field=models.BooleanField(default=True, help_text="False si l'utilisateur n'a aucun souvenir de son rêve cette nuit", verbose_name='A un souvenir du rêve'),
        ),
        migrations.AlterField(
            model_name='reve',
            name='audio',
            field=models.FileField(blank=True, help_text='Enregistrement audio du rêve (WAV)', null=True, upload_to='reves_audio/'),
        ),
    ]
