# Generated by Django 6.0.2 on 2026-03-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0009_reve_existence_souvenir_alter_reve_audio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emotion',
            new_name='ReveEmotion',
        ),
        migrations.RenameModel(
            old_name='EmotionCustom',
            new_name='ReveEmotionCustom',
        ),
        migrations.RenameModel(
            old_name='ImageModalite',
            new_name='ReveImageModalite',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='ReveTag',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='deja_ecrit_reve',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='name',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
