# Generated by Django 6.0.2 on 2026-03-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0011_questionnaire_user_reve_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='welcome_email_sent',
            field=models.BooleanField(default=False, help_text="Indique si l'email de bienvenue a été envoyé à la première connexion", verbose_name='Email de bienvenue envoyé'),
        ),
    ]
