# Generated by Django 6.0.2 on 2026-03-04 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0012_profil_welcome_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création du profil'),
            preserve_default=False,
        ),
    ]
