# Generated by Django 6.0.2 on 2026-03-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0013_profil_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un profil avec cet email existe déjà.'}, max_length=254, unique=True),
        ),
    ]
