# Generated by Django 6.0.2 on 2026-03-05 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0014_alter_profil_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('daily_reminder', 'Rappel quotidien - Enregistrer un rêve'), ('questionnaire_reminder', 'Rappel - Remplir le questionnaire'), ('general', 'Notification générale')], max_length=50, verbose_name='Type de notification')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la notification')),
                ('message', models.TextField(verbose_name='Message de la notification')),
                ('is_read', models.BooleanField(default=False, verbose_name='Notification lue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reves.profil')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
