# Generated by Django 6.0.2 on 2026-03-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_questionnaire_a_deja_travaille_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReveElementCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=120, verbose_name='Element')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_custom', to='polls.profil')),
            ],
            options={
                'verbose_name': 'Element personnalisé',
                'verbose_name_plural': 'Elements personnalisés',
                'ordering': ['libelle'],
                'unique_together': {('profil', 'libelle')},
            },
        ),
        migrations.AddField(
            model_name='reve',
            name='commentaire_libre',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire libre'),
        ),
        migrations.AddField(
            model_name='reve',
            name='elements_reve',
            field=models.JSONField(blank=True, default=list, help_text='Liste des éléments liés (travail, famille, amis, et personnalisés)', verbose_name='Elements liés au rêve'),
        ),
        migrations.AddField(
            model_name='reve',
            name='temps_reve',
            field=models.CharField(blank=True, choices=[('passe_lointain', 'Passé lointain'), ('passe_recent', 'Passé récent (dans la semaine)'), ('veille', 'Evénements de la veille'), ('futur_proche', 'Futur proche (dans la semaine)'), ('difficile', 'Difficile à dire / Pas liés')], max_length=20, null=True, verbose_name='Temporalité des éléments du rêve'),
        ),
    ]
