# Generated by Django 6.0.2 on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('reves', '0017_reveelementcustom_reve_elements_reve_and_more'),
	]

	operations = [
		migrations.AlterField(
			model_name='reve',
			name='temps_reve',
			field=models.CharField(
				blank=True,
				choices=[
					('passe_lointain', 'Passé lointain'),
					('passe_recent', 'Passé récent (dans la semaine)'),
					('veille', 'Evénements de la veille'),
					('futur_proche', 'Futur proche (dans la semaine)'),
					('futur_lointain', 'Futur lointain'),
					('difficile', 'Difficile à dire / Pas liés'),
				],
				max_length=20,
				null=True,
				verbose_name='Temporalité des éléments du rêve',
			),
		),
	]