# Generated by Django 6.0.2 on 2026-03-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_questionnaire_aide_autre_questionnaire_aide_medic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='genre',
            field=models.IntegerField(blank=True, choices=[(1, 'Femme'), (2, 'Homme'), (3, 'Autre')], null=True, verbose_name='Genre'),
        ),
    ]
