# Generated by Django 6.0.2 on 2026-03-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0020_alter_questionnaire_genre'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "UPDATE reves_questionnaire "
                "SET habitat = CASE "
                "WHEN habitat = 'rural' THEN '1' "
                "WHEN habitat = 'urbain' THEN '2' "
                "ELSE habitat END"
            ),
            reverse_sql=(
                "UPDATE reves_questionnaire "
                "SET habitat = CASE "
                "WHEN habitat = '1' THEN 'rural' "
                "WHEN habitat = '2' THEN 'urbain' "
                "ELSE habitat END"
            ),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='habitat',
            field=models.IntegerField(blank=True, choices=[(1, 'Rural'), (2, 'Urbain')], null=True, verbose_name="Environnement d'habitat"),
        ),
    ]
