# Generated by Django 6.0.2 on 2026-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0021_alter_questionnaire_habitat'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "UPDATE reves_questionnaire "
                "SET profession = NULL "
                "WHERE profession IS NOT NULL "
                "AND profession NOT IN ('101','102','103','104','201','202','203','204','205','301','302','303','304','305','401','402','403','501','502','503','504','601','602','603','604','605','701','702','703','704')"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='profession',
            field=models.IntegerField(blank=True, choices=[(101, "1.1 | Chefs d'entreprises, hors hôtellerie, restauration, commerce"), (102, "1.2 | Chefs d'entreprises, hôtellerie, restauration, commerce"), (103, '1.3 | Cadres dirigeants salariés, hors hôtellerie, restauration, commerce'), (104, '1.4 | Cadres dirigeants et gérants, hôtellerie, restauration, commerce'), (201, '2.1 | Ingénieurs et spécialistes des sciences, des techniques, des TIC'), (202, '2.2 | Médecins et professionnels de santé'), (203, '2.3 | Cadres administratifs, financiers et commerciaux'), (204, '2.4 | Professionnels de la justice, des sciences sociales et de la culture'), (205, "2.5 | Enseignants et professionnels de l'enseignement"), (301, '3.1 | Professions intermédiaires des sciences, techniques et TIC'), (302, '3.2 | Professions intermédiaires salariées de la santé'), (303, '3.3 | Professions intermédiaires de finance, vente et administration'), (304, '3.4 | Professions intermédiaires des services juridiques et sociaux'), (305, '3.5 | Sous-officiers des forces armées'), (401, '4.1 | Exploitants agricoles'), (402, '4.2 | Commerçants et assimilés'), (403, '4.3 | Artisans'), (501, '5.1 | Employés de bureau et assimilés'), (502, '5.2 | Employés de réception, guichetiers et assimilés'), (503, "5.3 | Aides-soignants, gardes d'enfants et aides-enseignants"), (504, '5.4 | Services de protection/sécurité et armées'), (601, '6.1 | Ouvriers qualifiés de la construction, sauf électriciens'), (602, '6.2 | Ouvriers qualifiés alimentation, bois, habillement'), (603, '6.3 | Ouvriers qualifiés métallurgie, mécanique, imprimerie, élec/électronique'), (604, '6.4 | Conducteurs de machines/installations fixes, assemblage'), (605, '6.5 | Conducteurs de véhicules et engins mobiles'), (701, '7.1 | Personnels de services et employés de commerces'), (702, '7.2 | Ouvriers peu qualifiés et manœuvres'), (703, "7.3 | Agents d'entretien"), (704, '7.4 | Ouvriers agricoles')], help_text='Choisir uniquement une sous-catégorie de profession', null=True, verbose_name='Profession (sous-catégorie)'),
        ),
    ]
