# Generated by Django 6.0.2 on 2026-03-16 10:50

from django.db import migrations, models


def migrate_temps_reve(apps, schema_editor):
    """Transfère les données existantes de temps_reve (CharField) vers les 6 BooleanFields."""
    Reve = apps.get_model('polls', 'Reve')
    mapping = {
        'passe_lointain': 'temps_passe_lointain',
        'passe_recent': 'temps_passe_recent',
        'veille': 'temps_veille',
        'futur_proche': 'temps_futur_proche',
        'futur_lointain': 'temps_futur_lointain',
        'difficile': 'temps_difficile',
    }
    for reve in Reve.objects.exclude(temps_reve__isnull=True).exclude(temps_reve=''):
        field = mapping.get(reve.temps_reve)
        if field:
            setattr(reve, field, True)
            reve.save(update_fields=[field])


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_questionnaire_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='reve',
            name='temps_difficile',
            field=models.BooleanField(default=False, verbose_name='Difficile à dire / Pas liés'),
        ),
        migrations.AddField(
            model_name='reve',
            name='temps_futur_lointain',
            field=models.BooleanField(default=False, verbose_name='Futur lointain'),
        ),
        migrations.AddField(
            model_name='reve',
            name='temps_futur_proche',
            field=models.BooleanField(default=False, verbose_name='Futur proche (dans la semaine)'),
        ),
        migrations.AddField(
            model_name='reve',
            name='temps_passe_lointain',
            field=models.BooleanField(default=False, verbose_name='Passé lointain'),
        ),
        migrations.AddField(
            model_name='reve',
            name='temps_passe_recent',
            field=models.BooleanField(default=False, verbose_name='Passé récent (dans la semaine)'),
        ),
        migrations.AddField(
            model_name='reve',
            name='temps_veille',
            field=models.BooleanField(default=False, verbose_name='Evénements de la veille'),
        ),
        migrations.RunPython(migrate_temps_reve, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='reve',
            name='temps_reve',
        ),
    ]
