# Generated by Django 6.0.2 on 2026-03-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0025_questionnaire_conj_csp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='besoin_som',
            field=models.TimeField(blank=True, null=True, verbose_name='En moyenne, de combien de temps de sommeil avez-vous besoin pour être en forme le lendemain ?'),
        ),
    ]
