# Generated by Django 6.0.2 on 2026-03-16 13:42
# Modified for PostgreSQL compatibility

from django.db import migrations, models
from datetime import time


def convert_integer_to_time(apps, schema_editor):
    """Convertir besoin_som de INTEGER (minutes) en TIME"""
    Questionnaire = apps.get_model('reves', 'Questionnaire')
    for q in Questionnaire.objects.all():
        if hasattr(q, 'besoin_som') and q.besoin_som is not None:
            try:
                # besoin_som était stocké en minutes (INTEGER)
                minutes = int(q.besoin_som)
                hours = minutes // 60
                mins = minutes % 60
                q.besoin_som_new = time(hour=hours, minute=mins)
                q.save()
            except (ValueError, TypeError):
                pass


def reverse_convert(apps, schema_editor):
    """Reverse: pas besoin de revenir"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0025_questionnaire_conj_csp_and_more'),
    ]

    operations = [
        # Ajouter colonne temporaire TimeField
        migrations.AddField(
            model_name='questionnaire',
            name='besoin_som_new',
            field=models.TimeField(blank=True, null=True),
        ),
        # Convertir les données (si nécessaire)
        migrations.RunPython(convert_integer_to_time, reverse_convert),
        # Supprimer l'ancienne colonne INTEGER
        migrations.RemoveField(
            model_name='questionnaire',
            name='besoin_som',
        ),
        # Renommer la nouvelle
        migrations.RenameField(
            model_name='questionnaire',
            old_name='besoin_som_new',
            new_name='besoin_som',
        ),
        # Ajouter verbose_name
        migrations.AlterField(
            model_name='questionnaire',
            name='besoin_som',
            field=models.TimeField(blank=True, null=True, verbose_name='En moyenne, de combien de temps de sommeil avez-vous besoin pour être en forme le lendemain ?'),
        ),
    ]
