# Generated by Django 6.0.2 on 2026-03-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0026_alter_questionnaire_besoin_som'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='det_1',
            field=models.IntegerField(blank=True, choices=[(1, 'En permanence'), (2, 'Souvent'), (3, 'Quelques fois'), (4, 'Rarement'), (5, 'Jamais')], null=True, verbose_name='Nerveux/nerveuse'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='det_2',
            field=models.IntegerField(blank=True, choices=[(1, 'En permanence'), (2, 'Souvent'), (3, 'Quelques fois'), (4, 'Rarement'), (5, 'Jamais')], null=True, verbose_name='Triste et abattu·e'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='det_3',
            field=models.IntegerField(blank=True, choices=[(1, 'En permanence'), (2, 'Souvent'), (3, 'Quelques fois'), (4, 'Rarement'), (5, 'Jamais')], null=True, verbose_name='Calme et détendu·e'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='det_4',
            field=models.IntegerField(blank=True, choices=[(1, 'En permanence'), (2, 'Souvent'), (3, 'Quelques fois'), (4, 'Rarement'), (5, 'Jamais')], null=True, verbose_name='Si découragé·e que rien ne pouvait vous remonter le moral'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='det_5',
            field=models.IntegerField(blank=True, choices=[(1, 'En permanence'), (2, 'Souvent'), (3, 'Quelques fois'), (4, 'Rarement'), (5, 'Jamais')], null=True, verbose_name='Heureux/heureuse'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_age',
            field=models.BooleanField(default=False, verbose_name='Votre âge'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_autre',
            field=models.BooleanField(default=False, verbose_name='Pour une autre raison'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_autre_precision',
            field=models.TextField(blank=True, null=True, verbose_name='Précisez autre raison de discrimination'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_contexte_autre',
            field=models.BooleanField(default=False, verbose_name='Lors d’une autre situation'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_contexte_education',
            field=models.BooleanField(default=False, verbose_name='A l’école, à l’université ou en formation'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_contexte_emploi',
            field=models.BooleanField(default=False, verbose_name='Lors d’une recherche d’emploi'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_contexte_famille',
            field=models.BooleanField(default=False, verbose_name='Dans le cadre familial'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_contexte_logement',
            field=models.BooleanField(default=False, verbose_name='Lors de la recherche d’un logement'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_contexte_sante',
            field=models.BooleanField(default=False, verbose_name='Chez un médecin, professionnel de santé ou à l’hôpital'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_contexte_travail',
            field=models.BooleanField(default=False, verbose_name='Sur votre lieu de travail'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_couleur_peau',
            field=models.BooleanField(default=False, verbose_name='Votre couleur de peau'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_genre',
            field=models.BooleanField(default=False, verbose_name='Votre sexe ou votre genre'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_orientation_sexuelle',
            field=models.BooleanField(default=False, verbose_name='Votre orientation sexuelle'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_origine_nationalite',
            field=models.BooleanField(default=False, verbose_name='Vos origines ou votre nationalité'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_presence',
            field=models.IntegerField(blank=True, choices=[(1, 'Oui, souvent'), (2, 'Oui, parfois'), (3, 'Non, jamais')], null=True, verbose_name='Pensez-vous avoir subi des traitements inégalitaires ou des discriminations au cours des 5 dernières années ?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_sante_mentale',
            field=models.BooleanField(default=False, verbose_name='Votre état de santé psychique, votre état de santé mentale'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_sante_physique',
            field=models.BooleanField(default=False, verbose_name='Votre état de santé physique ou un handicap'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='discri_situation_familiale',
            field=models.BooleanField(default=False, verbose_name='Votre situation de famille'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='perception_financiere',
            field=models.IntegerField(blank=True, choices=[(1, 'Vous êtes à l’aise'), (2, 'Ca va'), (3, 'C’est juste, il faut faire attention'), (4, 'Vous y arrivez difficilement'), (5, 'Vous ne pouvez pas y arriver sans faire de dette')], null=True, verbose_name='Actuellement, dans votre foyer, vous diriez que financièrement :'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='perception_mobilite',
            field=models.IntegerField(blank=True, choices=[(1, 'Moins bonne'), (2, 'Comparable'), (3, 'Meilleure')], null=True, verbose_name='Par rapport à vos parents au même âge, diriez-vous que votre situation sociale est :'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='perception_risque_pauvrete',
            field=models.IntegerField(blank=True, choices=[(1, 'Oui, plutôt'), (2, 'Non, plutôt pas'), (3, 'Je me considère déjà comme pauvre'), (4, 'Ne sait pas')], null=True, verbose_name='Pensez-vous qu’il y a un risque que vous deveniez pauvre dans les cinq prochaines années ?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='position_subjective_classe',
            field=models.IntegerField(blank=True, choices=[(1, 'Classes populaires'), (2, 'Classes moyennes modestes'), (3, 'Classes moyennes'), (4, 'Classes moyennes supérieures'), (5, 'Classes supérieures')], null=True, verbose_name='Aujourd’hui, si vous deviez vous situer socialement, vous diriez que vous appartenez plutôt à :'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='sante_generale',
            field=models.IntegerField(blank=True, choices=[(1, 'Très bon'), (2, 'Bon'), (3, 'Assez bon'), (4, 'Mauvais'), (5, 'Très mauvais')], null=True, verbose_name='Comment est votre état de santé en général ?'),
        ),
    ]
