# Generated by Django 6.0.2 on 2026-03-18 12:50

from django.db import migrations
from django.contrib.auth.models import Group


def create_recording_groups(apps, schema_editor):
    """Créer les deux groupes pour les modes d'enregistrement"""
    Group.objects.get_or_create(name='audio_recording')
    Group.objects.get_or_create(name='text_only')


def remove_recording_groups(apps, schema_editor):
    """Supprimer les groupes"""
    Group.objects.filter(name__in=['audio_recording', 'text_only']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0029_questionnaire_submission_number'),
    ]

    operations = [
        migrations.RunPython(create_recording_groups, remove_recording_groups),
    ]
