# Generated by Django 6.0.2 on 2026-04-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0031_alter_reve_audio_secure_upload_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='created_at_trick',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de référence questionnaire (temporaire)'),
        ),
    ]
