# Generated by Django 6.0.2 on 2026-04-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0032_profil_created_at_trick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reve',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ReveTag',
        ),
    ]
