# Generated by Django 6.0.2 on 2026-04-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0033_remove_reve_tags_delete_revetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reve',
            name='emotions_reve',
            field=models.ManyToManyField(blank=True, related_name='reves', to='reves.reveemotion', verbose_name='Émotions ressenties'),
        ),
    ]
