# Generated by Django 6.0.2 on 2026-04-03 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0034_alter_reve_emotions_reve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='dream_lucide',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='dream_nightmare',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='dream_pleasant',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='dream_recurrent',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='sleep_hours',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='sleep_quality',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='detresse_psychologique',
            field=models.IntegerField(blank=True, help_text='Calculé automatiquement à partir de det_1 à det_5. Score < 55 = détresse significative (Leplège et al., 1998)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score de détresse psychologique'),
        ),
    ]
