# Generated by Django 6.0.2 on 2026-04-10 09:04

from django.db import migrations


def update_emotions(apps, schema_editor):
    """Met à jour les émotions proposées"""
    ReveEmotion = apps.get_model('reves', 'ReveEmotion')
    
    # 1. Changer Appréhension → Dégout (ordre reste 3)
    apprehension = ReveEmotion.objects.filter(libelle='Appréhension').first()
    if apprehension:
        apprehension.libelle = 'Dégout'
        apprehension.emoji = '🤢'
        apprehension.save()
    
    # 2. Joie passe de l'ordre 5 à 6
    joie = ReveEmotion.objects.filter(libelle='Joie').first()
    if joie:
        joie.ordre = 6
        joie.save()
    
    # 3. Bonheur → Surprise avec ordre 5
    bonheur = ReveEmotion.objects.filter(libelle='Bonheur').first()
    if bonheur:
        bonheur.libelle = 'Surprise'
        bonheur.emoji = '😲'
        bonheur.ordre = 5
        bonheur.save()


def reverse_emotions(apps, schema_editor):
    """Revenir aux émotions précédentes"""
    ReveEmotion = apps.get_model('reves', 'ReveEmotion')
    
    # Inverser les changements
    degout = ReveEmotion.objects.filter(libelle='Dégout').first()
    if degout:
        degout.libelle = 'Appréhension'
        degout.emoji = '😰'
        degout.save()
    
    joie = ReveEmotion.objects.filter(libelle='Joie').first()
    if joie:
        joie.ordre = 5
        joie.save()
    
    surprise = ReveEmotion.objects.filter(libelle='Surprise').first()
    if surprise:
        surprise.libelle = 'Bonheur'
        surprise.emoji = '😄'
        surprise.ordre = 6
        surprise.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0035_remove_questionnaire_comments_and_more'),
    ]

    operations = [
        migrations.RunPython(update_emotions, reverse_emotions)
    ]
