# Generated by Django 6.0.2 on 2026-04-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0036_update_emotions_proposed'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='logement',
            field=models.IntegerField(blank=True, choices=[(1, 'Propriétaire'), (2, "Locataire d'un logement social"), (3, 'Locataire hors logement social, dans le parc privé'), (4, 'Logé·e gratuitement'), (5, 'Autre')], null=True, verbose_name='Concernant votre résidence principale, êtes-vous…'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='montant_loyer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quel est le montant de ce loyer ou de votre prêt par mois ?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pret',
            field=models.BooleanField(blank=True, null=True, verbose_name='Avez-vous un remboursement de prêt en cours pour votre résidence principale ?'),
        ),
    ]
