# Generated by Django 6.0.2 on 2026-06-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0039_public_uuid_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='consent_quote_expressions',
            field=models.BooleanField(default=False, help_text="J'autorise qu'une partie de mes expressions puisse être citée, étant entendu qu'il ne sera pas possible de m'identifier.  J'accepte que le son de mes enregistrements, une fois anonymisés et regroupés avec ceux des autres participant·es, soit analysé.", verbose_name="Autorize la citation d'expressions"),
        ),
    ]
