# Generated by Django 6.0.2 on 2026-07-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reves', '0040_alter_profil_consent_quote_expressions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='consent_sensitive_data',
            field=models.BooleanField(default=False, help_text='Je consens à la collecte et à l\'analyse des données sensibles que je choisis de partager concernant mon origine ou ma vie affective et sexuelle.', verbose_name='Consentement sur les données sensibles'),
        ),
    ]