apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres/pvc.yml
  - postgres/deployment.yml
  - postgres/service.yml
  - postgres/cronjob.yml
  - django/pvc.yml
  - django/deployment.yml
  - django/service.yml

commonLabels:
  owner: medialab
  app: journal-des-reves
