# Generated by Django 6.0.2 on 2026-02-20 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('F', 'Femme'), ('H', 'Homme'), ('NB', 'Non Binaire'), ('A', 'Autre')], max_length=15)),
                ('biography', models.CharField(max_length=1000)),
                ('birth_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)])),
                ('deja_ecrit_reve', models.BooleanField(default=True)),
                ('page_officiel', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(error_messages={'invalid': 'Saisissez une adresse de courriel valide'}, max_length=254)),
            ],
        ),
    ]
