# Generated by Django 6.0.2 on 2026-02-26 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='annee_naissance',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Année de naissance'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='genre',
            field=models.CharField(blank=True, choices=[('F', 'Femme'), ('H', 'Homme'), ('A', 'Autre')], max_length=1, null=True, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='niv_diplome',
            field=models.IntegerField(blank=True, choices=[(1, 'Aucun diplôme'), (2, "Certificat d'études primaires"), (3, 'BEPC, brevet élémentaire, brevet des collèges, DNB'), (4, 'CAP, BEP ou diplôme de niveau équivalent'), (5, "Brevet supérieur, professionnel, de technicien ou d'enseignement"), (6, 'Baccalauréat technologique ou professionnel'), (7, "Baccalauréat d'enseignement général"), (8, 'Capacité en droit, DAEU, ESEU'), (9, 'Bac +2 (BTS, DUT, DEUG, DEUST, etc.)'), (10, 'Bac +3 ou Bac +4 (Licence, Master, etc.)'), (11, 'Bac +5 (Master, DESS, DEA, grande école, etc.)'), (12, 'Doctorat de recherche')], null=True, verbose_name='Diplôme le plus élevé obtenu'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='profession',
            field=models.TextField(blank=True, help_text='Votre profession actuelle ou dernière profession', null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='revenus_tranche',
            field=models.IntegerField(blank=True, choices=[(1, 'Moins de 400 €'), (2, 'De 400 € à moins de 600 €'), (3, 'De 600 € à moins de 800 €'), (4, 'De 800 € à moins de 1 000 €'), (5, 'De 1 000 € à moins de 1 200 €'), (6, 'De 1 200 € à moins de 1 500 €'), (7, 'De 1 500 € à moins de 1 800 €'), (8, 'De 1 800 € à moins de 2 000 €'), (9, 'De 2 000 € à moins de 2 500 €'), (10, 'De 2 500 € à moins de 3 000 €'), (11, 'De 3 000 € à moins de 4 000 €'), (12, 'De 4 000 € à moins de 6 000 €'), (13, 'De 6 000 € à moins de 10 000 €'), (14, '10 000 € ou plus')], null=True, verbose_name='Revenus mensuels du ménage'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='travail_statut',
            field=models.IntegerField(blank=True, choices=[(1, 'En emploi'), (2, 'En études, formation ou stage'), (3, 'Au chômage'), (4, 'Retraité(e), préretraité(e)'), (5, 'Homme ou femme au foyer'), (6, 'Inactif(ve) pour invalidité'), (7, "Autre situation d'inactivité")], null=True, verbose_name='Situation principale vis-à-vis du travail'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Tous les jours'), ('often', 'Souvent'), ('sometimes', 'Parfois'), ('rarely', 'Rarement')], max_length=20, null=True, verbose_name='Fréquence de rappel des rêves'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='sleep_hours',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Heures de sommeil'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='sleep_quality',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Bon'), ('average', 'Moyen'), ('poor', 'Mauvais')], max_length=20, null=True, verbose_name='Qualité du sommeil'),
        ),
    ]
