# Generated by Django 6.0.2 on 2026-03-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='a_deja_travaille',
            field=models.BooleanField(blank=True, help_text='Avez-vous déjà travaillé au moins à mi-temps pendant au moins 6 mois ?', null=True, verbose_name='A déjà travaillé (6+ mois)'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='fonction_management',
            field=models.BooleanField(blank=True, help_text="Exercez-vous une fonction de management ou d'autorité ?", null=True, verbose_name='Fonction de management/autorité'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='habitat',
            field=models.CharField(blank=True, choices=[('rural', 'Rural'), ('urbain', 'Urbain')], max_length=10, null=True, verbose_name="Environnement d'habitat"),
        ),
    ]
