# Generated by Django 6.0.2 on 2026-03-13 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_alter_reve_temps_reve'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='aide_autre',
            field=models.BooleanField(default=False, verbose_name='Autre aide'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='aide_medic',
            field=models.BooleanField(default=False, verbose_name='Médicaments'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='aide_sommeil',
            field=models.BooleanField(blank=True, null=True, verbose_name='Utilisez-vous des aides pour dormir (médicaments, tisane, application de méditation, etc.) ?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='aide_tisane',
            field=models.BooleanField(default=False, verbose_name='Tisane'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='besoin_som',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)], verbose_name='En moyenne, de combien de temps de sommeil avez-vous besoin pour être en forme le lendemain ?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='cont_autre',
            field=models.BooleanField(default=False, verbose_name='Autres'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='cont_jeux',
            field=models.BooleanField(default=False, verbose_name='Jeux videos'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='cont_livres',
            field=models.BooleanField(default=False, verbose_name='Livres, journaux'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='cont_rien',
            field=models.BooleanField(default=False, verbose_name='Rien'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='cont_rs',
            field=models.BooleanField(default=False, verbose_name='Reseaux sociaux'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='cont_series_films',
            field=models.BooleanField(default=False, verbose_name='Series / films'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='cont_tv',
            field=models.BooleanField(default=False, verbose_name='Television'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='duree_eveil',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)], verbose_name='En général, combien de temps restez-vous éveillé(e) au cours de la nuit ?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='etendue_souvenir_reve',
            field=models.IntegerField(blank=True, choices=[(1, 'Une sensation'), (2, 'Un instant precis'), (3, 'Moins de la moitie de mon reve'), (4, 'Plus de la moitie de mon reve'), (5, "L'integralite")], null=True, verbose_name='Vous vous souvenez plutôt'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='freq_reves_not',
            field=models.IntegerField(blank=True, choices=[(1, 'Oui souvent'), (2, 'Quelques fois'), (3, 'Jamais')], null=True, verbose_name='Avant cette enquête, vous est-il arrivé de noter vos rêves ?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='heure_coucher',
            field=models.TimeField(blank=True, null=True, verbose_name='Le plus souvent, en semaine, à quelle heure éteignez-vous votre lampe pour dormir ?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='heure_reveil',
            field=models.TimeField(blank=True, null=True, verbose_name='Le plus souvent en semaine à quelle heure vous réveillez-vous ?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='img_coul',
            field=models.BooleanField(default=False, verbose_name='En couleur'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='img_flou',
            field=models.BooleanField(default=False, verbose_name='Floues'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='img_nb',
            field=models.BooleanField(default=False, verbose_name='En noir et blanc'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='img_net',
            field=models.BooleanField(default=False, verbose_name='Nettes'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='img_ns',
            field=models.BooleanField(default=False, verbose_name='Ne sait pas'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='latence_som',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)], verbose_name='Le plus souvent, combien de temps vous faut-il pour vous endormir ?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='mod_emot',
            field=models.BooleanField(default=False, verbose_name='Emotions ressenties'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='mod_img',
            field=models.BooleanField(default=False, verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='mod_pens',
            field=models.BooleanField(default=False, verbose_name='Pensees ou idees'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='mod_sens',
            field=models.BooleanField(default=False, verbose_name='Sensations du corps'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='mod_son',
            field=models.BooleanField(default=False, verbose_name='Sons, voix'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='nuits_reveil',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Combien de nuits par semaine cela vous arrive-t-il ?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pens_actu',
            field=models.BooleanField(default=False, verbose_name='Actualite'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pens_autre',
            field=models.BooleanField(default=False, verbose_name='Autre'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pens_autre_txt',
            field=models.TextField(blank=True, null=True, verbose_name='Precisez autre pensee'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pens_fam',
            field=models.BooleanField(default=False, verbose_name='Famille'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pens_fin',
            field=models.BooleanField(default=False, verbose_name='Situation financiere'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pens_proch',
            field=models.BooleanField(default=False, verbose_name='Proches'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pens_rien',
            field=models.BooleanField(default=False, verbose_name='Je ne pense pas a des choses en particulier'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pens_trav',
            field=models.BooleanField(default=False, verbose_name='Travail / etudes'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='reveil_nuit',
            field=models.BooleanField(blank=True, null=True, verbose_name='Vous arrive-t-il de vous réveiller la nuit avec des difficultés pour vous rendormir ?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='temps_du_reve',
            field=models.IntegerField(blank=True, choices=[(1, 'Du passe lointain'), (2, 'Du passe proche'), (3, 'Du present (de la veille)'), (4, 'Du futur (de ce qui pourrait arriver)'), (5, 'Pas de lien avec votre vie')], null=True, verbose_name="Vous avez l'impression de rêver davantage"),
        ),
    ]
